name: LootBox
version: '${project.version}'
main: fr.lootbox.LootBox
api-version: 1.19
authors: [ValMG]
description: Un simple plugin de lootbox
commands:
  box:
    description: Commande destinée aux modérateurs pour donner la lootbox et la poser
